# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todoapp_development
  host: localhost
  username: postgres
  password: 6dcbbcc4276f49c985021ba64ebb9c69

test:
  <<: *default
  database: todoapp_test
  host: localhost
  username: postgres
  password: 6dcbbcc4276f49c985021ba64ebb9c69

# En production sur Render, on utilise uniquement DATABASE_URL
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
