# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todoapp_development
  host: localhost
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>

test:
  <<: *default
  database: todoapp_test
  host: localhost
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *default
  # Render utilisera DATABASE_URL (fourni par le service Postgres)
  url: <%= ENV["DATABASE_URL"] %>
